# Generated by Django 2.0.9 on 2025-01-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='allocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cam_model', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='complaints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=200)),
                ('AUTHORITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.authority')),
            ],
        ),
        migrations.CreateModel(
            name='detections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=200)),
                ('CAMERA', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.camera')),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='places',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='suggestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('suggestion', models.CharField(max_length=200)),
                ('AUTHORITY', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.authority')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='PLACE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.places'),
        ),
        migrations.AddField(
            model_name='authority',
            name='LOGIN',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.login'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='AUTHORITY',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.authority'),
        ),
        migrations.AddField(
            model_name='allocation',
            name='PLACE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.places'),
        ),
    ]
