# Generated by Django 2.0.9 on 2025-01-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detections',
            name='message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
